### ISSUE TITLE
Slideout menu only on Phone

### ISSUE THREAD

**Issue by MickL** [Mango/slideout#126]
I would like to have the slideout menu only on Smartphone, while on all other resolutions bigger than X show the default menu within the layout.

Is this already implemented? Or do i have to write a window.resize function which creates and destroys the menu, and also moves it out of layout(#panel)?

**Comment by montogeek** [comment]
You can initialize Slideout only in mobile mode. On desktop display your current menu.

**Comment by pazguille** [comment]
Also, you could use mediaqueries:

```css
@media screen and (min-width: 780px) {
  .slideout-panel {
    margin-left: 256px;
  }

  .slideout-menu {
    display: block;
  }

  .btn-hamburger {
    display: none;
  }
}
```

Demo: http://codepen.io/anon/pen/xGEdvQ?editors=100
