### ISSUE TITLE
Box Connector

### ISSUE THREAD

**Issue by jyotishman** [Mango/slideout#19]
how to remove the connectors that are connected to each box?

**Comment by pazguille** [comment]
You should remove the pseudo-elements from `.box`.

```css
.box:before, .box:after {
  content: ' ';
  display: inline-block;
  width: 1px;
  height: 50px;
  border-left: 1px solid #4B5;
  position: absolute;
  left: 50%;
}
```
