### ISSUE TITLE
switch from push to slide over 

### ISSUE THREAD

**Issue by hendrikeng** [Mango/slideout#202]
Hey there first off all thanks for the great work, everything works so far.

I wanted to switch from a pushing menu (push main content) to a slide over menu (just covers the content) . I achieved it so far ..what doesn't work for sure now is the slide in animation since the menu just pops up  if i press the button.  I cant really figure out how to change it in the js. 

http://codepen.io/HendrikEng/pen/GNRQOL

**Comment by pazguille** [comment]
Hi @hendrikeng! Checkout it out: http://codepen.io/anon/pen/MbaoYy

It's a hack but works fine:
```css
.slideout-menu {
  position: fixed;
  left: -256px;
  top: 0;
  bottom: 0;
  z-index: 0;
  width: 256px;
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
  z-index:10;
}

.slideout-panel {
  position:relative;
  background:red;
  height:1500px;
  width:100%;
}

.slideout-open,
.slideout-open body,
.slideout-open .slideout-panel {
 overflow: hidden;
}

.slideout-open .slideout-menu {
  display: block;
}

#menu {
  background: green;
}

body {
  background: pink;
  margin: 0;
}

.toggle-button {
  float: right;
  margin: 10px;
}
```

```js
// FTW! :)
var menu = slideout.menu;
slideout.menu = slideout.panel;
slideout.panel = menu;
```
