### ISSUE TITLE
Right and left slide together

### ISSUE THREAD

**Issue by prajwalmr62** [Mango/slideout#224]
I was not able to add one `right slideout` and one `left slideout` for same panel. Is there any way to achieve it?

**Comment by jakdotspiral** [comment]
I was able to achieve this by using the event listeners _(refer to the API docs)_. Take the following (I based this upon their example).

```javascript
function closeSlideout(e) {
  e.preventDefault();
  slideoutMenu.close();
}

slideout
  .on('beforeopen', function() {
    this.panel.classList.add('is-open');
    this.menu.classList.add('is-open');
  })
  .on('open', function() {
    this.panel.addEventListener('click', closeSlideoutMenu);
  })
  .on('beforeclose', function() {
    this.panel.classList.remove('is-open');
    this.menu.classList.remove('is-open');
    this.panel.removeEventListener('click', closeSlideoutMenu);
  })
  .on('translate', function(translated) {
   this.menu.classList.add('is-visible');
  })
  .on('translateend', function() {
    this.menu.classList.remove('is-visible');
  });
```

This allows us to tell when the user is sliding the panel, and trigger some CSS to show _only_ the relevant menu. You might not need the `closeSlideout()` function and its associated code but I left it in anyway. Add the following to your CSS:

```css
.slideout-menu {
  opacity: 0;
  pointer-events: none;
}

.slideout-menu.is-visible,
.slideout-menu.is-open {
  opacity: 1;
  pointer-events: auto;
}
```

_Just FYI, support for _pointer-events_ is somewhat limited but should have enough coverage on touch devices._
