### ISSUE TITLE
Not Supporting Bootstrap

### ISSUE THREAD

**Issue by jaideepghosh-rz** [Mango/slideout#245]
I'm trying to include slideout in my bootstrap template, but slideout functionalities are conflicting with my template features.

**Comment by lakhman** [comment]
I had an issue with the modal not showing. The following css worked for me.

```css
body.modal-open {
  .slideout-panel {
    transform: none !important;
    z-index: unset;
    will-change: unset;
  }
}
```
