### ISSUE TITLE
Onclick slide is not smooth

### ISSUE THREAD

**Issue by satyajit9830** [Mango/slideout#74]
Hi,
The documentations is not smooth as like demo.
Please help me to fix it

Here is the demo link http://sevakart.com/kolkata/menu/

**Comment by pazguille** [comment]
Hi @satyajit9830,

You should add your own styles for `.slideout-panel` and `.slideout-menu`. The file sildeout.css gives you a basic layer of CSS.

For example:

```css
body {
  margin: 0;
}

.slideout-panel {
  background-color: red;
  min-height: 100%;
}
```
