### ISSUE TITLE
Opened sidebar as default

### ISSUE THREAD

**Issue by luke82** [Mango/slideout#77]
Hello,
is there a way to set a sidebar opened as defaut on large screen only? On others closed.
Thank you

**Comment by thecrentist** [comment]
Bump. I have been looking for this as well. Need it to be opened by default.

Thanks.

**Comment by pazguille** [comment]
You could use mediaqueries:

```css
@media screen and (min-width: 780px) {
  .slideout-panel {
    margin-left: 256px;
  }

  .slideout-menu {
    display: block;
  }

  .btn-hamburger {
    display: none;
  }
}
```

Demo: http://codepen.io/anon/pen/xGEdvQ?editors=100
